# Generated by Django 4.2.3 on 2023-07-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowDate', models.DateField()),
                ('diaryContents', models.ManyToManyField(to='scripts.script')),
            ],
        ),
    ]
