# Generated by Django 4.2.3 on 2023-07-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_alter_diary_id_alter_diary_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
