runtime: python311
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65

env_variables:
  DJANGO_SETTINGS_MODULE: "config.settings"

entrypoint: gunicorn -b :$PORT config.wsgi

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
