[tool.poetry]
name = "anylearn"
version = "0.1.0"
description = ""
authors = ["yuunseo <dbstj7457@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
