# Generated by Django 4.2.4 on 2023-08-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_remove_script_contents_script_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='contents',
            field=models.TextField(null=True),
        ),
    ]
