# Generated by Django 4.2.4 on 2023-08-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_alter_script_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='add_diary',
            field=models.IntegerField(null=True),
        ),
    ]
