# Generated by Django 4.2.4 on 2023-09-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_script_add_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='add_diary',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
