# Generated by Django 4.2.4 on 2023-09-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_alter_script_add_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='show_expr',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
