# Generated by Django 4.2.4 on 2023-09-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_script_show_expr'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='input_expr',
            field=models.TextField(default=0, null=True),
        ),
    ]
